name: flutter_utils_code
description: A Flutter utils package
version: 0.0.4
#author: Mr.pan <panzhoutao1@gmail.com>
homepage: https://github.com/panzhoutao/flutter_utils_code

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.0
  dio_log: ^2.0.0
  fluttertoast: ^8.0.5
  #  permission_handler: ^5.0.1+1
  provider: ^5.0.0
#  flutter_screenutil: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

